spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
  mail:
    host: smtp.gmail.com
    port: 587
    username: misterhurin@gmail.com
    password: ukwhprskpgbzdanw
    protocol: smtp
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

spring.jpa:
  hibernate.ddl-auto: update

application:
  security:
    jwt:
      secret-key: cb24f858d80b44012c2af75344f4cbcf4b33bc4ee40130240f17fc9e368fb4f5
      expiration: 86400000 #day
      refresh-token:
        expiration: 604800000 # 7 days

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true

custom:
  verification-code-expiration: 10 #minutes
  password-changing-link: "http://localhost:8080/online-shop/info/password/new"
  wishlist-products-on-sale-notification-link: "http://localhost:8080/online-shop/products/"
  sender-email: "online.shop.gmail.com"
#  change to non-project dir //done
  files-saving-path: "F://Work/ITworks/Java projects/Local file folder/"
