spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser

spring.jpa:
  hibernate.ddl-auto: create

application:
  security:
    jwt:
      secret-key: cb24f858d80b44012c2af75344f4cbcf4b33bc4ee40130240f17fc9e368fb4f5
      expiration: 86400000 #day
      refresh-token:
        expiration: 604800000 # 7 days
